name: Generate snake

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12 horas (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: victorgteixeira
          outputs: |
            dist/snake.svg
      - name: Push Snake to branch 'output'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
